### ISSUE TITLE
Calling 'depends_on :python3' is deprecated!

### ISSUE THREAD

**Issue by cecilyen** [cartr/homebrew-qt4#43]
Found the following error message while updating brew today. I just did an upgrade of brew yesterday.

```
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/pyqt@4.rb:8:in `<class:PyqtAT4>'
Please report this to the cartr/qt4 tap!
```

**Comment by damitr** [comment]
Same error for me also 
```
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/pyqt@4.rb:8:in `<class:PyqtAT4>'
Please report this to the cartr/qt4 tap!
```
